### ISSUE TITLE
(Diego) Compléter compte-rendu du 2016-02-03

### ISSUE THREAD

**Issue by davidonlaptop** [bigdatafoundation/qngene#3]

**Comment by pirateparrot** [comment]
Que est-ce que j'ai fait.
Préparer et envoyer rapport avec choix de projet de maîtrise à Alain.
Me renseigner sur GWAS, ADAM, AVRO, Genomiques en général.

Qu'est-ce que je prévois avoir terminée d'ici à la prochaine réunion?
Avoir analysé 5 catégories de GWAS du site OMIC Tools
Commencer avec mapping des tables CARTaGENE

Quels obstacles je rencontre en ce moment ?
Pas de fichier CARTaGENE avec structure de données
Pas encore contacté Beatriz
