### ISSUE TITLE
Lire et expérimenter avec les fonctions gwas de plink (chapitre 11 et 19)

### ISSUE THREAD

**Issue by davidonlaptop** [bigdatafoundation/qngene#8]

**Comment by davidonlaptop** [comment]
http://pngu.mgh.harvard.edu/~purcell/plink/anal.shtml
http://pngu.mgh.harvard.edu/~purcell/plink/dosage.shtml

**Comment by momozaza** [comment]
this task was an initial comprehension of PLINK and its major functionnalities.

**Comment by aapril** [comment]
ok
